#!/usr/bin/env bash
#
# Agenda — Docker-only one-shot startup.
# Usage: ./start.sh [--no-build]
#
# - Creates .env with generated secrets on first run (compose network hosts)
# - Builds and starts the full stack
# - Migrations run via the `migrate` service; optional seed afterwards
#
set -euo pipefail

cd "$(dirname "$0")"

NO_BUILD=false
for arg in "$@"; do
  if [ "$arg" = "--no-build" ]; then
    NO_BUILD=true
  fi
done

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m!!\033[0m %s\n' "$*" >&2; }

if ! command -v docker >/dev/null 2>&1; then
  err "Docker is required but was not found in PATH."
  exit 1
fi

if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  err "Docker Compose is required but was not found."
  exit 1
fi

gen_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

gen_b64() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n'
  else
    gen_hex
  fi
}

# --- 1. Ensure .env --------------------------------------------------------
if [ ! -f .env ]; then
  log "No .env found — generating one with fresh secrets (Docker network hosts)."
  PG_PASS="$(gen_hex | cut -c1-24)"
  cat > .env <<EOF
# Auto-generated by start.sh (Docker Compose only). Edit as needed.
POSTGRES_USER=line
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=line_promotion
DATABASE_URL=postgres://line:${PG_PASS}@postgres:5432/line_promotion

BETTER_AUTH_SECRET=$(gen_b64)
BETTER_AUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000

WORKER_LINE_URL=http://worker-line:4000
SCB_SLIP_URL=http://scb-slip:8000

PROMPTPAY_ID=0838433623
SCB_API_KEY=$(gen_hex)
BILLING_WEBHOOK_SECRET=$(gen_hex)
BILLING_OPS_TOKEN=$(gen_hex)
CRON_SECRET=$(gen_hex)
INTERNAL_API_KEY=$(gen_hex)
SESSION_ENCRYPTION_KEY=$(gen_hex)

PAYMENT_TTL_MINUTES=30
PAYMENT_GRACE_MINUTES=15
SUBSCRIPTION_GRACE_DAYS=3

RESEND_API_KEY=
RESEND_FROM_EMAIL=Agenda <noreply@yourdomain.com>
SENTRY_DSN=
APP_DOMAIN=your.domain.example
ACME_EMAIL=you@example.com

WORKER_PORT=4000
LINE_DEVICE=ANDROIDSECONDARY
LINE_SESSION_PATH=/data/session/session.json
SCHEDULER_TICK_SECONDS=30

MAX_HOT_SESSIONS=200
MAX_BOOT_RESTORE_SESSIONS=1
SESSION_IDLE_EVICT_MS=300000
AUTO_REPLY_CYCLE_SEC=30
AUTO_REPLY_TICK_MS=100
HIBERNATE_AFTER_AUTO_REPLY_POLL=true
EOF
  log ".env created."
else
  log "Using existing .env."
fi

# --- 2. Build & start (migrate runs as a one-shot dependency) --------------
if [ "$NO_BUILD" = true ]; then
  log "Starting containers (skip build)..."
  "${DC[@]}" up -d
else
  log "Building and starting containers (this may take a while on first run)..."
  "${DC[@]}" up -d --build
fi

# --- 3. Optional settings seed ---------------------------------------------
log "Seeding settings (idempotent)..."
if ! "${DC[@]}" run --rm migrate pnpm seed; then
  err "Seed failed. Check: ${DC[*]} logs migrate"
  exit 1
fi

# --- 4. Done ----------------------------------------------------------------
log "All set."
printf '\n\033[1;32m  Web: \033[0m http://localhost:3000\n\n'
printf 'Sign up, then open Connect LINE in the dashboard to link your account.\n'
printf 'Logs:  %s logs -f\n' "${DC[*]}"
printf 'Stop:  %s down\n' "${DC[*]}"
